"""RPG - List Library.

Author: Caden VanV
Version: 10/4/2024
"""


# Character names
rpg_names = ('Aaron', 'Abraham', 'Adam', 'Alan', 'Alec',
             'Alex', 'Alexander', 'Amos', 'Andrew', 'Anthony',
             'Andy', 'Arnold', 'Arthur', 'Avery', 'Barry', 'Bart',
             'Bartholomew', 'Benjamin', 'Bernard', 'Benny',
             'Bill', 'Bob', 'Bobby', 'Brad', 'Bradley', 'Brent',
             'Brett', 'Brian', 'Bruce', 'Burt', 'Byron', 'Caleb',
             'Calvin', 'Carl', 'Chad', 'Chadwick', 'Chandler',
             'Charles', 'Charlie', 'Chris', 'Christopher', 'Chuck',
             'Clark', 'Cliff', 'Cole', 'Colin', 'Cory', 'Dale', 'Daniel',
             'Darrel', 'Darren', 'Dave', 'David', 'Dennis',
             'Derek', 'Devin', 'Dick', 'Dirk', 'Donald', 'Donny',
             'Doug', 'Douglas', 'Drake', 'Drew', 'Dwain',
             'Dwight', 'Edgar', 'Edward', 'Edwin', 'Elliot',
             'Eric', 'Ernest', 'Ernie', 'Frank', 'Franklin', 'Fred',
             'Frederick', 'Gary', 'George', 'Geoffrey', 'Glenn',
             'Gordon', 'Graham', 'Grant', 'Greg', 'Gregory',
             'Harold', 'Harry', 'Harvey', 'Heidi', 'Henry',
             'Howard', 'Hunter', 'Ichabod', 'Isaac', 'Ivan', 'Jack',
             'James', 'Jason', 'Jay', 'Jeff', 'Jeremy', 'Jerome',
             'Jim', 'Jimmy', 'John', 'Jonathan', 'Jordan', 'Joe',
             'Joel', 'Joseph', 'Joshua', 'Justin', 'Keith',
             'Kareem', 'Kenneth', 'Kevin', 'Kirk', 'Kurt', 'Kyle',
             'Lance', 'Larry', 'Lawrence', 'Lee', 'Leonard',
             'Lester', 'Lionel', 'Llewellyn', 'Lou', 'Louis', 'Lyle',
             'Mark', 'Mashall', 'Martin', 'Marty', 'Marvin', 'Matt',
             'Matthew', 'Maurice', 'Michael', 'Nathan',
             'Nathaniel', 'Ned', 'Neil', 'Nicholas', 'Nick', 'Nolan',
             'Norbert', 'Norman', 'Oliver', 'Oscar', 'Oswald',
             'Patrick', 'Paul', 'Peter', 'Phillip', 'Quincy', 'Ralph',
             'Randy', 'Ray', 'Raymond', 'Reuben', 'Richard',
             'Rick', 'Ricky', 'Robbie', 'Robert', 'Robin', 'Rodney',
             'Roger', 'Ron', 'Ronald', 'Ronnie', 'Russell', 'Rusty',
             'Ryan', 'Sam', 'Samuel', 'Scott', 'Shawn', 'Sheldon',
             'Sidney', 'Simon', 'Spencer', 'Stanley', 'Steve',
             'Steven', 'Stewart', 'Taylor', 'Ted', 'Theodore',
             'Thomas', 'Tim', 'Timothy', 'Todd', 'Tom', 'Tommy',
             'Tony', 'Travis', 'Trent', 'Trevor', 'Tyler', 'Ulysses',
             'Victor', 'Wallace', 'Wally', 'Ward', 'Wayne',
             'Wendall', 'William', 'Xavier', 'Yancy', 'Abby',
             'Abigail', 'Alexandria', 'Alice', 'Alicia', 'Allison',
             'Alyssa', 'Andrea', 'Angelica', 'Angie', 'Anna',
             'Annabelle', 'Anne', 'Ariel', 'Audrey', 'Barbara',
             'Beatrice', 'Becky', 'Bernadette', 'Beth', 'Bethany',
             'Betty', 'Betsy', 'Beverly', 'Bonnie', 'Brianna',
             'Bridget', 'Brooke', 'Carly', 'Carol', 'Carrie',
             'Catherine', 'Cathy', 'Cecilia', 'Celeste', 'Charlene',
             'Charlotte', 'Christine', 'Christina', 'Cindy', 'Connie',
             'Constance', 'Crystal', 'Cynthia', 'Daisy', 'Danielle',
             'Deanna', 'Deirdre', 'Diana', 'Diane', 'Donna',
             'Dora', 'Dorothy', 'Dot', 'Dotty', 'Edith', 'Edna',
             'Elaine', 'Eliza', 'Elizabeth', 'Ellen', 'Emily', 'Emma',
             'Erica', 'Erin', 'Erma', 'Ernestine', 'Esmerelda',
             'Esther', 'Evelyn', 'Fanny', 'Fiona', 'Florence', 'Fran',
             'Francis', 'Gabby', 'Gabriel', 'Gail', 'Georgette',
             'Georgina', 'Gina', 'Ginger', 'Gloria', 'Grace',
             'Gwen', 'Hannah', 'Harriet', 'Heather', 'Helen',
             'Henrietta', 'Ida', 'Isabelle', 'Jackie', 'Jane', 'Janet',
             'Janie', 'Jacqueline', 'Jasmine', 'Jeanette', 'Jennifer',
             'Jenny', 'Jessica', 'Jo', 'Jody', 'Josie', 'Jolene', 'Josephine',
             'Joyce', 'Judy', 'Judith', 'Julie', 'Karen', 'Katie', 'Kathy',
             'Katherine', 'Kathleen', 'Kelly', 'Kimberly', 'Laura',
             'Laurie', 'Leslie', 'Lila', 'Linda', 'Lisa', 'Lois', 'Lucille',
             'Lucy', 'Lydia', 'Lynn', 'Mabel', 'Mavis', 'Mae',
             'Mandy', 'Margaret', 'Marge', 'Maria', 'Martha',
             'Martina', 'Mary', 'Maxine', 'Melanie', 'Melinda',
             'Melissa', 'Melody', 'Meredith', 'Michelle', 'Millicent',
             'Millie', 'Mindy', 'Minnie', 'Molly', 'Monica', 'Nadine',
             'Nancy', 'Natalie', 'Nell', 'Nicole', 'Olive', 'Olivia', 'Pam',
             'Pamela', 'Patricia', 'Patty', 'Paula', 'Pauline', 'Phyllis',
             'Polly', 'Rachel', 'Rebecca', 'Regina', 'Renee', 'Rita',
             'Rose', 'Rosie', 'Ruth', 'Sabrina', 'Sally', 'Samantha',
             'Sandra', 'Sandy', 'Sarah', 'Sharon', 'Shelby', 'Sherrie',
             'Sophia', 'Sophie', 'Stacey', 'Stephanie', 'Sue',
             'Susan', 'Suzanne', 'Tabitha', 'Tammy', 'Tanya',
             'Teresa', 'Thelma', 'Tina', 'Tracy', 'Trina', 'Tricia',
             'Trish', 'Ursula', 'Valerie', 'Vanessa', 'Veronica', 'Vicky',
             'Victoria', 'Viola', 'Violet', 'Wanda', 'Wendy', 'Yolanda',
             'Yvette', 'Yvonne', 'Zelda', 'Zoe')

# Generic enemy types
generic_enemy_types = ('Wolf', 'Orc Brute', 'Bandit', 'Mercenary', 'Skeleton',
                       'Goblin', 'Bear', 'Troll', 'Giant', 'Giant Spider',
                       'Slime')

# Settlement name parts
settlement_suf = ('shire', 'sburg', 'sfeld', 'ville',
                  'ton', 'bury', 'market', 'haven',
                  'chester', 'kirk', 'val', 'vale',
                  'dale', 'dalle', 'bie', 'by', 'wick',
                  'wich', 'mont', 'low', 'berg', 'berry',
                  'court', 'thorpe', 'bec', 'fleur',
                  'burn', 'avon')

settlement_pref = ('Fair', 'Moon', 'Fell', 'Gare', 'Ird', 'Ash', 'Birch',
                   'Beech', 'Oak', 'Willow', 'Cherry', 'Spruce', 'Maple',
                   'White', 'Blue', 'Red', 'Orange', 'Din', 'Dun', 'Nor',
                   'Sur', 'Est', 'Wel', 'Gard')
